name: main
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: "build"
        working-directory: demos
        run: |
          yarn install
          CI=false yarn build
      - name: "publish"
        run: |
          npx -p "@getmeli/cli" meli upload ./demos/build \
            --url "https://meli.my-company.com" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_SITE: "f08a1a93-df71-4328-8e86-cdf06f732a43"
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
